name: Main Action

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout (git clone) Repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Run Tests
              run: npm test
            
            - name: Capture Test Output
              run: tee test_output.txt
              continue-on-error: true

            - name: Display Test Output
              if: always()
              run: cat test_output.txt

        